# Generated by Django 2.1.7 on 2019-04-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
